### ISSUE TITLE
Warning: 'wsrep_desync' is already ON.

### ISSUE THREAD

**Issue by akuzminsky** [twindb/backup#7] opened 2017-01-03 16:21 UTC
* TwinDB Backup version: 2.5.0

### Description

`twindb-backup` sets `wsrep_desync` to ON when it takes a backup from Percona XtraDB Cluster. if the backup job fails on whatever reason `wsrep_desync` if not reverted to OFF.

Next `twindb-backup` run will produce a warning:
```
/usr/lib/python2.7/site-packages/twindb_backup/backup.py:49: Warning: 'wsrep_desync' is already ON.
c.execute("set global wsrep_desync=ON")
```

**Comment by mkryva** [comment] 2017-08-31 21:32
Can't reproduce. It seems, that bug was fixed by Ovais Tariq:
https://github.com/twindb/backup/commit/2f5731d3bb05639a20de83a9b16e29a6aa843ea7

**Closed by mkryva** 2017-08-31 21:32 UTC
